modLoader="javafml" 
loaderVersion="[40,)" 
license="All rights reserved"
[[mods]] 
modId="mint" 
version="${file.jarVersion}" 
displayName="Mint" 
logoFile="examplemod.png"
credits="Mint, brought to you by ZAPtron" 
authors="ZAPtron" 
description='''
Mint
A mod that adds coins!
'''
[[dependencies.mint]] 
    modId="forge" 
    mandatory=true 
    versionRange="[40,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.mint]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mint]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1802.5.5-build.567,)"

[[dependencies.mint]]
    modId = "rhino"
    mandatory = true
    versionRange = "[1802.2.1-build.255,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.mint]]
    modId = "architectury"
    mandatory = true
    versionRange = "[4.10.88,)"
    ordering = "AFTER"
    side = "BOTH"
